apiVariant: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    multiLabels: 
      app: mongodb
    templates:
      metadata: 
        labels: 
          app: mongodb
        spec: 
          containers:
            - name: mongodb
              image: mongo:4.4.5
              ports: 
                - 27017