apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  selector:
    matchLabels: 
      app: api
  template:
    metadata: 
      labels: 
        app: api
    spec: 
      containers:
        - name: api
          image: gildofj/api-bootcamp-produto-gildo:v1
          ports: 
           - containerPort: 8080
          env: 
            - name: MONGODB_URI
              value: mongodb://mongouser:mongopwd@localhost:27017/admin